### ISSUE TITLE
Exceptions when no license is installed on device

### ISSUE THREAD

**Issue by alperenkose** [PaloAltoNetworks/pan-os-upgrade-assurance#44]
## Describe the bug

Expired licenses and free disk space checks produce exceptions when there is no license (support and other licenses) installed on device.

```
Traceback (most recent call last):
  File "examples/readiness_checks/run_readiness_checks.py", line 90, in <module>
    check_readiness = check_node.run_readiness_checks(
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/check_firewall.py", line 724, in run_readiness_checks
    check_result = self._check_method_mapping[check_type](**check_config)  # (**) would pass dict config values as seperate parameters to method.
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/check_firewall.py", line 222, in check_expired_licenses
    licenses = self._node.get_licenses()
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/firewall_proxy.py", line 372, in get_licenses
    licenses = response['licenses']['entry']
TypeError: 'NoneType' object is not subscriptable
```

```
Traceback (most recent call last):
  File "examples/readiness_checks/run_readiness_checks.py", line 90, in <module>
    check_readiness = check_node.run_readiness_checks(
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/check_firewall.py", line 724, in run_readiness_checks
    check_result = self._check_method_mapping[check_type](**check_config)  # (**) would pass dict config values as seperate parameters to method.
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/check_firewall.py", line 514, in check_free_disk_space
    available_versions = self._node.get_available_image_data()
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/firewall_proxy.py", line 860, in get_available_image_data
    image_data = self.op_parser(cmd="request system software check")
  File "/Users/akose/Development/paloalto/pan-os-upgrade-assurance/panos_upgrade_assurance/firewall_proxy.py", line 65, in op_parser
    raw_response = self.op(cmd, xml=False, cmd_xml=not cmd_in_xml, vsys=self.vsys)
  File "/Users/akose/Library/Caches/pypoetry/virtualenvs/panos-upgrade-assurance-uG-9sGEi-py3.8/lib/python3.8/site-packages/panos/firewall.py", line 242, in op
    return super(Firewall, self).op(
  File "/Users/akose/Library/Caches/pypoetry/virtualenvs/panos-upgrade-assurance-uG-9sGEi-py3.8/lib/python3.8/site-packages/panos/base.py", line 4047, in op
    element = self.xapi.op(cmd, vsys, False, extra_qs, retry_on_peer=retry_on_peer)
  File "/Users/akose/Library/Caches/pypoetry/virtualenvs/panos-upgrade-assurance-uG-9sGEi-py3.8/lib/python3.8/site-packages/panos/base.py", line 3899, in method
    raise the_exception
panos.errors.PanDeviceXapiError: Failed to check upgrade info due to Unknown error. Please check network connectivity and try again.
```

**Comment by alperenkose** [comment]
Maybe we can do something for the expired licenses check only which is related to the licensing as well, and return a relevant exception (not TypeError) or response accordingly. And for the others we may leave a note on documentation.

**Comment by FoSix** [comment]
OK, so maybe let's do like this: add a built-in check, not configurable, always run before we run the checks from a list. This check would make sure the device is licensed. If it's not - it would thrown an exception that would inform a user about that. This way we would bale out before running anything as most of the checks do not make sense on a non licensed device.

We could also add this check before snapshots - same thing.

@alperenkose - any thoughts?
